# Production Environment Properties
spring.datasource.driverClassName=org.postgresql.Driver

# We forcefully map these to prevent falling back to the local H2 database config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Disable the H2 Console for security in production
spring.h2.console.enabled=false

# Render handles SSL for Postgres, you might need to append ?sslmode=require 
# to your JDBC url if it's strict, but usually Render's internal connections don't require it.
